services:
  bds:
    image: itzg/minecraft-bedrock-server:latest
    environment:
      - EULA=TRUE
      - VERSION=LATEST
      - TZ=America/New_York
      - SERVER_NAME=DelperRealm
      - GAMEMODE=survival
      - FORCE_GAMEMODE=survival
      - DIFFICULTY=peaceful
      - ALLOW_CHEATS=true
      - MAX_PLAYERS=4
    ports:
      - "19132:19132/udp"
    restart: 'unless-stopped'
    volumes:
      - /mnt/d/bedrock/data:/data
    stdin_open: true
    tty: true