version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server:latest
    environment:
      - EULA=TRUE
      - VERSION=LATEST
      - TZ=America/New_York
      - GAMEMODE=creative
      - DIFFICULTY=normal
    ports:
      - "19132:19132/udp"
    restart: 'unless-stopped'
    volumes:
      - //d/data:/data
    stdin_open: true
    tty: true